### ISSUE TITLE
Approach grid - not all Boards are listed in the selection dropdown

### ISSUE THREAD

**Issue by yoda-da** [agilist-ai/Neelix-for-Jira-Cloud#2] opened 2019-08-06 03:25 UTC
- Load approach Grid
- Click on Boards button for query type
- The dropdown list does not contain all board

**Comment by agilist-ai** [comment] 2019-08-06 13:18
Thank you for reporting. The issue is resolved in 2.2.10 release.

**Closed as completed by agilist-ai** 2019-08-06 13:18 UTC
Labels: bug
