### ISSUE TITLE
Contextual search screen monitor indicators administration - once created, cannot edit filter link

### ISSUE THREAD

**Issue by yoda-da** [agilist-ai/Neelix-for-Jira-Cloud#3] opened 2019-08-06 03:27 UTC
- Having created a metrics monitor, cannot edit the filter

**Comment by agilist-ai** [comment] 2019-08-06 10:40
Thank you for reporting. The issue is resolved in 2.2.10 release.

**Closed as completed by agilist-ai** 2019-08-06 10:40 UTC
Labels: bug
